create table if not exists public.knowledge_topic_generations (
  id bigint generated by default as identity primary key,
  cache_hash text not null unique,
  mode text not null check (mode in ('summary','questions')),
  topic text not null,
  fragment_ids jsonb not null default '[]',
  exam_options jsonb,
  summary text,
  questions jsonb,
  sources jsonb default '[]',
  created_by text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  use_count integer not null default 1
);

create index if not exists knowledge_topic_generations_last_used_idx
  on public.knowledge_topic_generations (last_used_at desc);

alter table public.knowledge_topic_generations enable row level security;

create policy knowledge_topic_generations_authenticated_read
  on public.knowledge_topic_generations
  for select
  to authenticated
  using (true);
