create table if not exists public.ai_document_indexes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  drive_file_id text not null,
  file_name text not null,
  file_fingerprint text not null,
  page_count integer not null default 0,
  topics jsonb not null default '[]'::jsonb,
  model text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, drive_file_id, file_fingerprint)
);

create index if not exists ai_document_indexes_file_idx
  on public.ai_document_indexes(user_id, drive_file_id, updated_at desc);

create table if not exists public.ai_index_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  drive_file_id text not null,
  file_name text not null,
  mime_type text not null,
  file_fingerprint text not null,
  status text not null default 'pending'
    check (status in ('pending','running','paused','completed','cancelled','error')),
  total_pages integer not null default 0,
  chunk_pages integer not null default 3,
  total_chunks integer not null default 0,
  next_chunk integer not null default 0,
  processed_pages integer not null default 0,
  topics jsonb not null default '[]'::jsonb,
  error_message text,
  model text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists ai_index_jobs_user_file_idx
  on public.ai_index_jobs(user_id, drive_file_id, updated_at desc);

create index if not exists ai_index_jobs_active_idx
  on public.ai_index_jobs(status, updated_at desc);

alter table public.ai_document_indexes enable row level security;
alter table public.ai_index_jobs enable row level security;

drop policy if exists "Users can read own document indexes" on public.ai_document_indexes;
create policy "Users can read own document indexes"
  on public.ai_document_indexes for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own index jobs" on public.ai_index_jobs;
create policy "Users can read own index jobs"
  on public.ai_index_jobs for select
  to authenticated
  using (auth.uid() = user_id);