-- Knowledge Base v1: persistent ingest jobs for large documents
create table if not exists public.knowledge_ingest_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id bigint references public.knowledge_documents(id) on delete cascade,
  drive_file_id text not null,
  file_name text not null,
  file_fingerprint text not null,
  status text not null default 'pending' check (status in ('pending','running','paused','completed','cancelled','error')),
  total_pages integer,
  chunk_pages integer not null default 3,
  total_chunks integer,
  next_chunk integer not null default 0,
  processed_pages integer not null default 0,
  error_message text,
  processing_version text not null default 'knowledge-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);
create index if not exists idx_knowledge_ingest_jobs_user_status on public.knowledge_ingest_jobs(user_id,status,updated_at desc);
create index if not exists idx_knowledge_ingest_jobs_drive on public.knowledge_ingest_jobs(drive_file_id);
alter table public.knowledge_ingest_jobs enable row level security;
drop policy if exists knowledge_ingest_jobs_select_own on public.knowledge_ingest_jobs;
create policy knowledge_ingest_jobs_select_own on public.knowledge_ingest_jobs for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists knowledge_ingest_jobs_insert_own on public.knowledge_ingest_jobs;
create policy knowledge_ingest_jobs_insert_own on public.knowledge_ingest_jobs for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists knowledge_ingest_jobs_update_own on public.knowledge_ingest_jobs;
create policy knowledge_ingest_jobs_update_own on public.knowledge_ingest_jobs for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
