-- Reconstruido por introspección del esquema vivo de Supabase (proyecto ytwemlejamslvsulnvam)
-- el 2026-09-19. Estas 9 migraciones se habían aplicado directamente contra producción sin
-- quedar nunca versionadas en git:
--   create_core_tables, create_user_profiles_roles, lock_down_profile_trigger_function,
--   lock_profile_trigger_execution, revoke_profile_trigger_rpc, fix_profiles_admin_rls_recursion,
--   move_is_admin_private_schema, allow_authenticated_profile_policy_check,
--   create_ai_usage_tracking.
-- Este archivo NO es el SQL original de esas migraciones (no se pudo recuperar el historial) —
-- es una reconstrucción equivalente del estado final resultante, generada consultando tablas,
-- RLS, políticas, funciones y triggers reales en la base. Se consolidan acá en un solo archivo
-- porque el objetivo es que el esquema completo quede versionado, no reproducir cada paso
-- intermedio (algunos de esos pasos, a juzgar por los nombres, fueron intentos revertidos
-- entre sí, como "lock_profile_trigger_execution" / "revoke_profile_trigger_rpc").
-- A partir de este punto, cualquier cambio de esquema debe ir en una migración nueva.

-- ── Esquema privado: funciones de seguridad que no se exponen por la API de datos ──
create schema if not exists private;

-- ── oauth_tokens: token de Google Drive, fila única compartida (id = 'rossana') ────
create table if not exists public.oauth_tokens (
  id text primary key default 'rossana',
  access_token text,
  refresh_token text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.oauth_tokens enable row level security;
-- Sin políticas: solo accesible vía service_role desde la Edge Function "oauth"/"drive".

-- ── facultad_tracking: qué se hizo con cada archivo de la bandeja de Facultad ──────
create table if not exists public.facultad_tracking (
  file_id text primary key,
  file_name text not null,
  status text not null check (status in ('clasificado', 'ignorado')),
  destino_folder_id text,
  destino_nombre text,
  updated_at timestamptz not null default now()
);
alter table public.facultad_tracking enable row level security;
-- Sin políticas: solo accesible vía service_role desde la Edge Function "drive".

-- ── profiles: rol (ADMIN/USER) de cada usuario autenticado ────────────────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users (id),
  full_name text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
  on public.profiles for select
  to authenticated
  using (id = auth.uid());

-- private.is_admin(): SECURITY DEFINER para poder chequear el rol ADMIN desde una política
-- RLS de profiles sin caer en recursión infinita al volver a consultar la propia tabla.
create or replace function private.is_admin()
returns boolean
language sql
stable security definer
set search_path to 'public'
as $function$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'ADMIN'
  );
$function$;

drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles"
  on public.profiles for select
  to authenticated
  using (private.is_admin());

-- Al crearse un usuario nuevo en auth.users, se le crea automáticamente su fila en profiles.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    'USER'
  )
  on conflict (id) do nothing;
  return new;
end;
$function$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── ai_usage: panel "Consumo IA" — tokens y costo estimado por llamada a OpenAI ────
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users (id),
  user_email text,
  action text not null,
  stage text,
  model text not null,
  input_tokens bigint not null default 0,
  cached_input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  total_tokens bigint not null default 0,
  estimated_cost_usd numeric not null default 0,
  response_id text,
  topic text,
  file_count integer not null default 0,
  file_names text[],
  metadata jsonb
);
alter table public.ai_usage enable row level security;
-- Sin políticas: solo accesible vía service_role desde la Edge Function "drive".

create index if not exists ai_usage_created_at_idx on public.ai_usage using btree (created_at desc);
create index if not exists ai_usage_user_id_idx on public.ai_usage using btree (user_id);
create index if not exists ai_usage_action_idx on public.ai_usage using btree (action);
