-- Knowledge base v1: isolated prototype schema.
-- Intentionally NOT applied to production.

create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  drive_file_id text not null unique,
  file_name text not null,
  mime_type text,
  fingerprint text,
  title text,
  source_type text not null default 'other',
  subject_area text,
  page_count integer not null default 0,
  processing_status text not null default 'pending',
  processing_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_fragments (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.knowledge_documents(id) on delete cascade,
  page_start integer not null,
  page_end integer not null,
  content text not null,
  content_hash text,
  extraction_method text,
  created_at timestamptz not null default now(),
  check (page_start > 0 and page_end >= page_start)
);

create table if not exists public.knowledge_concepts (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text not null unique,
  description text,
  concept_type text,
  parent_id bigint references public.knowledge_concepts(id) on delete set null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_concept_aliases (
  id bigint generated by default as identity primary key,
  concept_id bigint not null references public.knowledge_concepts(id) on delete cascade,
  alias text not null,
  normalized_alias text not null,
  unique (concept_id, normalized_alias)
);

create table if not exists public.knowledge_fragment_concepts (
  fragment_id bigint not null references public.knowledge_fragments(id) on delete cascade,
  concept_id bigint not null references public.knowledge_concepts(id) on delete cascade,
  relevance numeric(5,4),
  evidence_type text,
  primary key (fragment_id, concept_id)
);

create table if not exists public.knowledge_document_concepts (
  document_id bigint not null references public.knowledge_documents(id) on delete cascade,
  concept_id bigint not null references public.knowledge_concepts(id) on delete cascade,
  coverage numeric(5,4),
  source_role text,
  page_start integer,
  page_end integer,
  primary key (document_id, concept_id)
);

create table if not exists public.knowledge_concept_relations (
  id bigint generated by default as identity primary key,
  concept_id bigint not null references public.knowledge_concepts(id) on delete cascade,
  related_concept_id bigint not null references public.knowledge_concepts(id) on delete cascade,
  relation_type text not null,
  weight numeric(5,4),
  unique (concept_id, related_concept_id, relation_type),
  check (concept_id <> related_concept_id)
);

create index if not exists idx_kf_document_pages
  on public.knowledge_fragments(document_id, page_start, page_end);

create index if not exists idx_kfc_concept
  on public.knowledge_fragment_concepts(concept_id);

create index if not exists idx_kdc_concept
  on public.knowledge_document_concepts(concept_id);

create index if not exists idx_kcr_related
  on public.knowledge_concept_relations(related_concept_id);

create index if not exists idx_kc_parent
  on public.knowledge_concepts(parent_id);

create index if not exists idx_kca_alias
  on public.knowledge_concept_aliases(normalized_alias);


-- Shared academic knowledge: authenticated users may read the prototype.
-- No anonymous access is granted.
alter table public.knowledge_documents enable row level security;
alter table public.knowledge_fragments enable row level security;
alter table public.knowledge_concepts enable row level security;
alter table public.knowledge_concept_aliases enable row level security;
alter table public.knowledge_fragment_concepts enable row level security;
alter table public.knowledge_document_concepts enable row level security;
alter table public.knowledge_concept_relations enable row level security;

create policy "knowledge_documents_authenticated_read"
  on public.knowledge_documents for select to authenticated using (true);
create policy "knowledge_fragments_authenticated_read"
  on public.knowledge_fragments for select to authenticated using (true);
create policy "knowledge_concepts_authenticated_read"
  on public.knowledge_concepts for select to authenticated using (true);
create policy "knowledge_concept_aliases_authenticated_read"
  on public.knowledge_concept_aliases for select to authenticated using (true);
create policy "knowledge_fragment_concepts_authenticated_read"
  on public.knowledge_fragment_concepts for select to authenticated using (true);
create policy "knowledge_document_concepts_authenticated_read"
  on public.knowledge_document_concepts for select to authenticated using (true);
create policy "knowledge_concept_relations_authenticated_read"
  on public.knowledge_concept_relations for select to authenticated using (true);
